### ISSUE TITLE
Conflicting comms cape header pins information for RS485

### ISSUE THREAD

**Issue by jeettrivedi** [beagleboard/capes#10]
While scrolling through the Beagle Cape Header Pins  [spreadsheet](https://docs.google.com/spreadsheets/d/1fE-AsDZvJ-bBwzNBj1_sPDrutvEvsmARqFwvbw_HkrE/edit#gid=1518010293), I noticed that `RS485.TX/UART4 TX` has been incorrectly mapped to P9.12 instead of P9.13 (as shown in the [schematic](https://github.com/beagleboard/capes/blob/master/beaglebone/Comms/Comms_Cape_sch.pdf)).

Its a simple enough of a fix but I figured I would bring it to the attention of the maintainers so that it is rectified. I'm happy to make a pull request with the correction.

**Comment by jadonk** [comment]
@jeettrivedi I don't see anywhere it is mapped to P9.12. Can you be more explicit? It seems all the documentation shows P9.11 for RX and P9.13 for TX.

**Comment by jeettrivedi** [comment]
@jadonk I just checked and it seems that the mistake has been corrected in the [spreadsheet](https://docs.google.com/spreadsheets/d/1fE-AsDZvJ-bBwzNBj1_sPDrutvEvsmARqFwvbw_HkrE/edit#gid=1518010293). I will close this issue now. Thanks for bringing this to my attention.
