### ISSUE TITLE
RE: The LoadCape and Docs.pdf or schematic.pdf...

### ISSUE THREAD

**Issue by silver2row** [beagleboard/capes#4]
Hello Sir,

Um...whenever you have time, please add some .pdf schematics of this bad-to-the-bone LoadCape. 

Seth

P.S. Thank you for your time.

**Comment by silver2row** [comment]
Hello Once More,

Seth here. I was trying to make this LoadCape work. I am not well informed on sinks as is. I keep reading about them when I have time. 

...

Is there a snippet to start, e.g. Adafruit_BBIO. If not, that is okay. I will keep searching for current sinks and see what I can derive.

Seth

P.S. If you ever find time, please try to establish a working .pdf of the this Cape. Thank you again, sir/ma'am.

**Comment by silver2row** [comment]
Hello,

I got some help from someone on the mfg. forums site. I am closing this issue.

Seth

**Comment by RyanBishop545** [comment]
silver2row could you please give a link to the information you have found?
